[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/oliverdaniels/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
Traceback (most recent call last):
  File "book_search.py", line 38, in <module>
    tokenizer_jp = Tokenizer()
                   ^^^^^^^^^^^
  File "janome/tokenizer.py", line 184, in __init__
  File "janome/system_dic.py", line 55, in instance
  File "janome/sysdic/__init__.py", line 83, in mmap_entries
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/27/xlq5rrfn01vfpxhdy3bydb2m0000gn/T/_MEIs7bLkZ/janome/sysdic/entries_compact0.py'
[36319] Failed to execute script 'book_search' due to unhandled exception: [Errno 2] No such file or directory: '/var/folders/27/xlq5rrfn01vfpxhdy3bydb2m0000gn/T/_MEIs7bLkZ/janome/sysdic/entries_compact0.py'
[36319] Traceback:
Traceback (most recent call last):
  File "book_search.py", line 38, in <module>
    tokenizer_jp = Tokenizer()
                   ^^^^^^^^^^^
  File "janome/tokenizer.py", line 184, in __init__
  File "janome/system_dic.py", line 55, in instance
  File "janome/sysdic/__init__.py", line 83, in mmap_entries
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/27/xlq5rrfn01vfpxhdy3bydb2m0000gn/T/_MEIs7bLkZ/janome/sysdic/entries_compact0.py'

